# Generated by Django 5.0.2 on 2024-02-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quadrilateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Figure', models.ImageField(upload_to='media/')),
                ('Sides', models.TextField()),
                ('Angles', models.TextField()),
                ('Diagonals', models.TextField()),
            ],
        ),
    ]
